version: '3'

services:
    web:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./src:/var/www/html
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - php
    php:
      image: phalconphp/php-fpm:7.0
      volumes:
          - ./src:/var/www/html
      links:
          - database
      depends_on:
          - database

    database:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql

        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=phalcon

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8888:80"
        links:
            - database
        depends_on:
            - database
        environment:
            - PMA_HOST=database

volumes:
    mysql-data:
